In [32]:
import crater_math as cm
import our_tools
import pandas as pd

df = pd.read_csv("Datasets/meteorite_data.csv")
ice = df
ice['KE'] = cm.solveKinEnergy(df['mass'], 20)
ice['diameter'] = cm.solveDiameter(1,1,1,ice['KE'], cm.dicProjectileDensity["ice"], cm.dicTargetDensity["sedimentary"])
ice

,name,mass,GeoLocation,KE,diameter
0,Aachen,21.0,"(50.775000, 6.083330)",4.20,0.081538
1,Aarhus,720.0,"(56.183330, 10.233330)",144.00,0.230589
2,Abee,107000.0,"(54.216670, -113.000000)",21400.00,1.003780
3,Acapulco,1914.0,"(16.883330, -99.900000)",382.80,0.307409
4,Achiras,780.0,"(-33.166670, -64.950000)",156.00,0.236081
5,Adhi Kot,4239.0,"(32.100000, 71.800000)",847.80,0.388396
6,Adzhi-Bogdo (stone),910.0,"(44.833330, 95.166670)",182.00,0.247031
7,Agen,30000.0,"(44.216670, 0.616670)",6000.00,0.690587
8,Aguada,1620.0,"(-31.600000, -65.233330)",324.00,0.292695
9,Aguila Blanca,1440.0,"(-30.866670, -64.550000)",288.00,0.282730
10,Aioun el Atrouss,1000.0,"(16.398060, -9.570280)",200.00,0.253978
11,Aïr,24000.0,"(19.083330, 8.383330)",4800.00,0.646721
12,Akaba,779.0,"(29.516670, 35.050000)",155.80,0.235992
13,Akbarpur,1800.0,"(29.716670, 77.950000)",360.00,0.301906
14,Akwanga,3000.0,"(8.916670, 8.433330)",600.00,0.350847
15,Akyumak,50000.0,"(39.916670, 42.816670)",10000.00,0.802535
16,Al Rais,160.0,"(24.416670, 39.516670)",32.00,0.148159
17,Al Zarnkh,700.0,"(13.660330, 28.960000)",140.00,0.228686
18,Alais,6000.0,"(44.116670, 4.083330)",1200.00,0.430181
19,Albareto,2000.0,"(44.650000, 11.016670)",400.00,0.311408
20,Alberta,625.0,"(2.000000, 22.666670)",125.00,0.221190
21,Alby sur Chéran,252.0,"(45.821330, 6.015330)",50.40,0.169336
22,Aldsworth,700.0,"(51.783330, -1.783330)",140.00,0.228686
23,Aleppo,3200.0,"(36.233330, 37.133330)",640.00,0.357570
24,Alessandria,908.0,"(44.883330, 8.750000)",181.60,0.246871
25,Alexandrovsky,9251.0,"(50.950000, 31.816670)",1850.20,0.488599
26,Alfianello,228000.0,"(45.266670, 10.150000)",45600.00,1.253907
27,Allegan,32000.0,"(42.533330, -85.883330)",6400.00,0.703820
28,Allende,2000000.0,"(26.966670, -105.316670)",400000.00,2.374815
29,Almahata Sitta,3950.0,"(20.745750, 32.412750)",790.00,0.380414
...,...,...,...,...,...
38252,Youndegin,3800000.0,"(-32.100000, 117.716670)",760000.00,2.868211
38253,Youxi,218000.0,"(26.060000, 118.010000)",43600.00,1.237476
38254,Ysleta,140700.0,"(31.650000, -106.183330)",28140.00,1.087953
38255,Yucca 015,3.0,"(34.819700, -114.276100)",0.60,0.046006
38256,Yucca 016,25.9,"(34.826580, -114.277630)",5.18,0.086726
38257,Yucca 017,200.0,"(34.819230, -114.277350)",40.00,0.158208
38258,Yudoma,7600.0,"(60.000000, 140.000000)",1520.00,0.461152
38259,Zacatecas (1792),1000000.0,"(22.816670, -102.566670)",200000.00,1.936854
38260,Zaffra,3000.0,"(35.000000, -94.750000)",600.00,0.350847
38261,Zag (b),300.0,"(27.333330, -9.333330)",60.00,0.178245
38262,Zagora,50000.0,"(30.366670, -5.850000)",10000.00,0.802535
38263,Zakłodzie,8680.0,"(50.762780, 22.866110)",1736.00,0.479530
38264,Zapaliname,85000.0,"(25.009440, -100.750000)",17000.00,0.938078
38265,Zapotitlán Salinas,27.7,"(18.333330, -97.500000)",5.54,0.088457
38266,Zaragoza,162000.0,"(41.650000, -0.866670)",32400.00,1.134006
38267,Zegdou,6700.0,"(29.750000, -4.500000)",1340.00,0.444371
38268,Zelfana,1058.0,"(32.158330, 4.633330)",211.60,0.258225
38269,Zenda,3700.0,"(42.513330, -88.489440)",740.00,0.373168
38270,Zerga,76.0,"(20.250000, -12.683330)",15.20,0.119027
38271,Zerhamra,630000.0,"(29.858610, -2.645000)",126000.00,1.690763
38272,Zerkaly,16000.0,"(52.133330, 81.966670)",3200.00,0.574022
38273,Zhaoping,2000000.0,"(24.233330, 111.183330)",400000.00,2.374815
38274,Zhigansk,900000.0,"(68.000000, 128.300000)",180000.00,1.877758
38275,Zhongxiang,100000.0,"(31.200000, 112.500000)",20000.00,0.984004
38276,Zillah 001,1475.0,"(29.037000, 17.018500)",295.00,0.284733
38277,Zillah 002,172.0,"(29.037000, 17.018500)",34.40,0.151344
38278,Zinder,46.0,"(13.783330, 8.966670)",9.20,0.102687
38279,Zlin,3.3,"(49.250000, 17.666670)",0.66,0.047314
38280,Zubkovsky,2167.0,"(49.789170, 41.504600)",433.40,0.318840
38281,Zulu Queen,200.0,"(33.983330, -115.683330)",40.00,0.158208